// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HobbyRepositoryCore.Models;

public partial class ActivityUser
{
    public int Id { get; set; }

    public string MemberId { get; set; }

    public string ActivityId { get; set; }

    public string ReviewStatus { get; set; }

    public string Role { get; set; }

    public virtual Activity Activity { get; set; }

    public virtual Member Member { get; set; }
}