// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HobbyRepositoryCore.Models;

public partial class ActivityImage
{
    public int Id { get; set; }

    public string ActivityId { get; set; }

    public string ActivityImage1 { get; set; }

    public bool IsCover { get; set; }

    public DateTime UploadTime { get; set; }

    public virtual ICollection<Activity> Activities { get; set; } = new List<Activity>();
}