// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HobbyRepositoryCore.Models;

public partial class Category
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string TypeName { get; set; }

    public virtual ICollection<Activity> Activity { get; set; } = new List<Activity>();
}