// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HobbyRepositoryCore.Models;

public partial class Member
{
    public string Id { get; set; }

    public string Name { get; set; }

    public string NickName { get; set; }

    public string Gender { get; set; }

    public string Account { get; set; }

    public string PassWord { get; set; }

    public string IdentityCard { get; set; }

    public DateTime? Birthday { get; set; }

    public string Address { get; set; }

    public string AcitveCity { get; set; }

    public string ActiveArea { get; set; }

    public string Phone { get; set; }

    public string HeadShot { get; set; }

    public string PersonalProfile { get; set; }

    public string Status { get; set; }

    public string OnlineStatus { get; set; }

    public DateTime CreationDate { get; set; }

    public DateTime? LastSignIn { get; set; }

    public virtual ICollection<ActivityUser> ActivityUser { get; set; } = new List<ActivityUser>();

    public virtual ICollection<Comment> Comment { get; set; } = new List<Comment>();

    public virtual ICollection<MsgBoard> MsgBoard { get; set; } = new List<MsgBoard>();

    public virtual ICollection<Wish> Wish { get; set; } = new List<Wish>();
}